---
name: test action
on:
  push:

jobs:
  test-action:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.tag-generator.outputs.tags }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: generate-version
        with:
          version: 1.0.0
          container-repository: test-repo
          container-name: test-name
  publish:
    runs-on: ubuntu-latest
    needs: test-action
    steps:
      - run: echo ${{ needs.test-action.outputs.tags }}
